// Assessment List Array

export let assessmentList = [
  {
    title: "Math Assessment",
    profession_type: "Job",
    date: "20 Apr 23",
    duration_time: "00",
    questions_number: "00",
    profile_name: ["LP"]
  },
  {
    title: "Math Assessment",
    profession_type: "Job",
    date: "20 Apr 23",
    duration_time: "00",
    questions_number: "00",
    profile_name: ["LP", "LP", "LP"],
    total_profile: "324"
  },
  {
    title: "Math Assessment",
    profession_type: "Job",
    date: "20 Apr 23",
    duration_time: "00",
    questions_number: "00",
    profile_name: ["LP", "LP", "LP"],
    total_profile: "324"
  },
  {
    title: "Math Assessment",
    profession_type: "Job",
    date: "20 Apr 23",
    duration_time: "00",
    questions_number: "00",
    profile_name: ["LP", "LP", "LP"],
    total_profile: "324"
  },
  {
    title: "Math Assessment",
    profession_type: "Job",
    date: "20 Apr 23",
    duration_time: "00",
    questions_number: "00",
    profile_name: ["LP", "LP", "LP"],
    total_profile: "32,4090"
  }
]


export let dialogData = [
  { title: 'Algorithms' },
  { title: 'Analytical Skills' },
  { title: 'Big Data' },
  { title: 'Calculating' },
  { title: 'Compiling Statistics' },
  { title: 'Data Analytics' },
  { title: 'Data Mining' },
  { title: 'Database Design' },
  { title: 'Database Management' },
  { title: 'Documentation' },
  { title: 'Modeling' },
  { title: 'Modification' },
  { title: 'Needs Analysis' },
  { title: 'Quantitative Research' },
  { title: 'Quantitative Reports' },
  { title: 'Statistical Analysis' },
  { title: 'Applications' },
  { title: 'Certifications' },
  { title: 'Coding' },
  { title: 'Computing' },
  { title: 'Configuration' },
  { title: 'Customer Support' },
  { title: 'Debugging' },
  { title: 'Design' },
  { title: 'Development' },
  { title: 'Hardware' },
  { title: 'Implementation' },
  { title: 'Information Technology' },
  { title: 'Infrastructure' },
  { title: 'Languages' },
  { title: 'Maintenance' },
  { title: 'Network Architecture' },
  { title: 'Network Security' },
  { title: 'Networking' },
  { title: 'New Technologies' },
  { title: 'Operating Systems' },
  { title: 'Programming' },
  { title: 'Restoration' },
  { title: 'Security' },
  { title: 'Servers' },
  { title: 'Software' },
  { title: 'Solution Delivery' },
  { title: 'Storage' },
  { title: 'Structures' },
  { title: 'Systems Analysis' },
  { title: 'Technical Support' },
  { title: 'Technology' },
  { title: 'Testing' },
  { title: 'Tools' },
  { title: 'Training' },
  { title: 'Troubleshooting' },
  { title: 'Usability' },
  { title: 'UI/UX and Design' },
  { title: 'No of Question' },
  { title: 'Benchmarking' },
  { title: 'Budget Planning' },
  { title: 'Engineering' },
  { title: 'Fabrication' },
  { title: 'Following Specifications' },
  { title: 'Operations' },
  { title: 'Performance Review' },
  { title: 'Project Planning' },
  { title: 'Quality Assurance' },
  { title: 'Quality Control' },
  { title: 'Scheduling' },
  { title: 'Task Delegation' },
  { title: 'Task Management' },
  { title: 'Blogging' },
  { title: 'Digital Photography' },
  { title: 'Digital Media' },
  { title: 'Facebook' },
  { title: 'Instagram' },
  { title: 'Networking' },
  { title: 'Pinterest' },
  { title: 'SEO' },
  { title: 'Social Media Platforms' },
  { title: 'Twitter' },
  { title: 'Web Analytics' },
  { title: 'Client Relations' },
  { title: 'Email' },
  { title: 'Requirements Gathering' },
  { title: 'Research' },
  { title: 'Subject Matter Experts (SMEs)' },
  { title: 'Technical Documentation' }
]